In [1]:
import torch
"""
torch.Tensor 是这个包的核心类。
如果设置它的属性 .requires_grad 为 True，那么它将会追踪对于该张量的所有操作。
当完成计算后可以通过调用 .backward()，来自动计算所有的梯度。
这个张量的所有梯度将会自动累加到.grad属性。
grad_fn操作历史；
"""

'\ntorch.Tensor 是这个包的核心类。\n如果设置它的属性 .requires_grad 为 True，那么它将会追踪对于该张量的所有操作。\n当完成计算后可以通过调用 .backward()，来自动计算所有的梯度。\n这个张量的所有梯度将会自动累加到.grad属性。\ngrad_fn操作历史；\n'

In [2]:
x = torch.ones(2, 2, requires_grad=True)  #requires_grad默认为False
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
z = y * y * 3
out = z.mean()
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
#TODO计算雅可比向量积?