In [1]:
from __future__ import print_function
import torch

In [7]:
#创建
#创建空
x = torch.empty(5,3)
#创建随机
x = torch.rand(5,3)
#直接根据数据创建
x = torch.tensor([5.5,3])
#还可以通过现有的 Tensor 来创建，此⽅方法会默认重⽤用输⼊入 Tensor 的一些属性，例例如数据类型。
x = x.new_ones(5,3)
x = torch.randn_like(x)
#可以自定义数据类型来覆盖。
x = x.new_ones(5,3,dtype = torch.float64)
x = torch.randn_like(x,dtype = torch.float64)
print(x)

tensor([[ 1.3064,  0.8918, -1.0655],
        [-0.4778, -0.1840,  0.3989],
        [-0.1274, -0.9207, -2.7950],
        [-1.1536, -0.8079, -0.7330],
        [-0.1664, -1.0906, -0.7179]], dtype=torch.float64)


In [8]:
#属性
#获取 Tensor 的形状
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [15]:
#运算
#加法
#同型形式1——直接加
y = torch.rand(5, 3)
#print(x + y)
#同型形式2——add函数
#print(torch.add(x, y))
#同型形式3——原位/原地操作（in-place）
y.add_(x)

tensor([[ 1.4005,  1.4855, -0.4312],
        [-0.1011,  0.6049,  0.6622],
        [-0.0116, -0.2573, -2.1454],
        [-0.5326, -0.0159, -0.6919],
        [ 0.6041, -0.4467,  0.1923]])

In [19]:
#索引操作
print(x[:, 1])
#改变形状
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(4,4,-1)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
#仅包含一个元素的tensor，可以使用.item()来得到对应的python数值
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5412,  0.5990,  0.5724,  0.5496])
torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4, 1])
